version: '3.8'

services:
  server:
    build: 
      context: ./server
      target: ${NODE_ENV:-development}
    ports:
      - "3005:3005"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-rootpassword}
      - DB_NAME=${DB_NAME:-vacation_db}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_secret_key
    depends_on:
      - db
      - redis

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3005

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=vacation_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
