version: '3'
services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=vacation_db
  client:
    build: ./client
    ports:
      - "3000:3000"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vacation_db
    volumes:
      - ./server/sql.init:/docker-entrypoint-initdb.d/init.sql
